### PR TITLE
PR: Instructions for GooseMod, extra hyperlinks

### PR DESCRIPTION
**Pull request by couleurm**

### CODE REVIEW

**Comment by hackermare** [comment]
Looks good. Where are the images hosted though?

**Comment by couleurm** [comment]
I pasted them in, so github!

**Comment by hackermare** [comment]
Will they stay there once you remove your fork?

**Comment by couleurm** [comment]
there's only one way to find out ps: saved the images just incase

**Comment by hackermare** [comment]
Well... That was an unfortunate timing. RIP GooseMod.

**Comment by couleurm** [comment]
Yup, do you know any other mod clients to use your plugin?

**Comment by hackermare** [comment]
BetterDiscord is the only one I could find. If you find a client you'd like the plugin to be ported to, let me know.

**Pull request merged**
